tenant:
  hostname: "presalesapjdev.int-az-au.webmethods.io"   # webMethodsIO Integration hostname or ip address
  port: "443"                                       # webMethodsIO Integration port
  admin_username: "joseph.nightingale@softwareag.com"                     # webMethodsIO Integration user  
  type: "dev"                                         #DEV