tenant:
  hostname: "presalesapjdev.int-az-au.webmethods.io"   # webMthodsIO Integration hostname or ip address
  port: "443"                                       # webMthodsIO Integration port
  admin_username: "joseph.nightingale@softwareag.com"                     # webMthodsIO Integration user  
  type: "prod"                                         #PROD